default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_library_development

test:
  <<: *default
  database: movie_library_test

production:
  primary:
    <<: *default
    database: movie_library_production
    username: movie_library
    password: <%= ENV["MOVIE_LIBRARY_DATABASE_PASSWORD"] %>